# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: The Elsevier LaTeX Class in Org-Mode
#+SUBTITLE: (The modification of the Schnorr's original template)
#+AUTHOR: Lucas Mello Schnorr, MB 

#+STARTUP: overview indent
#+LANGUAGE: en
#+OPTIONS: H:3 creator:nil timestamp:nil skip:nil toc:nil num:t ^:nil ~:~
#+OPTIONS: author:nil title:nil date:nil
#+TAGS: noexport(n) deprecated(d) ignore(i)
#+EXPORT_SELECT_TAGS: export 
#+EXPORT_EXCLUDE_TAGS: noexport 


#+LATEX_CLASS: ELSEVIER

# ##### MB note: nicer/default style of the pdf
# #+LATEX_CLASS_OPTIONS: [final,12pt]
#+LATEX_CLASS_OPTIONS: [sort&compress,final,onecolumn, 5p,times]

# ##### MB note: if you want to use engraved you need to disable this package...
# #+LATEX_HEADER: \usepackage{lineno}
# #+LATEX_HEADER: \linenumbers
# #+LATEX_HEADER: \modulolinenumbers[1]

# ##### MB note: these packages are included in default =org-latex-default-packages-alist=
# #+LATEX_HEADER: \usepackage[utf8]{inputenc}
# #+LATEX_HEADER: \usepackage[T1]{fontenc}


#+LATEX_HEADER: \usepackage{color}	
#+LATEX_HEADER: \usepackage{hyperref,xspace}
#+LATEX_HEADER: \usepackage[tight,footnotesize]{subfigure}
#+LATEX_HEADER: \usepackage{tabularx}

# You need at least Org 9 and Emacs 24 to make this work.
# If you do, just type make (thanks Luka Stanisic for this).
# You'll also need to install texlive-publishers to get acmart.cls

* Elsevier configuration for org export + ignore tag (Start Here)  :noexport:

#+begin_src emacs-lisp :results output :session :exports both
(add-to-list 'load-path ".")
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))
(add-to-list 'org-latex-classes
             '("ELSEVIER"
               "\\documentclass{elsarticle}"
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))


#+end_src

In order to be sure that the compilation process will succeed,
it's better to explicitely define =org-latex-pdf-process= here:

#+begin_src emacs-lisp :results output :session :exports both
; setting pdflatex process for bibtex citation approach
(setq org-latex-pdf-process '("pdflatex -shell-escape -interaction=nonstopmode %f"
                              "bibtex %b" 
                              "pdflatex -shell-escape -interaction=nonstopmode %f" 
                              "pdflatex -shell-escape -interaction=nonstopmode --synctex=-1 %f"))
#+end_src

** Caption of the table below the table
Use =describe-variable= to see the details of usage of
=org-latex-caption-above= variable (you can set ''caption above'' behaviour
separately for different types of items (tables, images, etc.)

#+begin_src emacs-lisp :results output :session :exports both
(setq org-latex-caption-above nil)
#+end_src

** Bibliography/citation engine

# ##### MB note: additional tags for two alternative citation engines
#+OPTIONS: tags:nil
#+TAGS: { @orgciteEngine(o) purelatexEngine(b)}
# ##### MB note: exclude the style you do NOT want to use by adding it to EXCLUDEd_TAGS
# #####    - if you want to use bibtex-like citing style, put @orgciteEngine in the line below
# #####    - if you want to use org-cite citing engine, put purelatexEngine in the line below
#+EXCLUDE_TAGS: purelatexEngine noexport

*** Citation - option 1: =cite-org=                 :ignore:@orgciteEngine:
# ##### MB note: For details have look here:
# #####          - https://orgmode.org/manual/Citation-export-processors.html
# #####          - https://www.overleaf.com/learn/latex/Bibtex_bibliography_styles#Table_of_stylename_values
# ##### Provided choosing bibtex processor you may also use styles 
# ##### added in this repository: elsarticle-harv, elsarticle-num-names, elsarticle-num

# ### MB note:  setting latex compilation for cite-org citation approach
#+BIBLIOGRAPHY: ./refs.bib
# Choosing style defined in ~/Zotero/styles #+CITE_EXPORT: csl elsevier-american-chemical-society-without-doi.csl
#+CITE_EXPORT: bibtex elsarticle-num


* *The Paper (preamble/configurations)*                              :ignore:
** Latex configurations                                             :ignore:
#+BEGIN_EXPORT latex
\journal{Information Sciences}
#+END_EXPORT
** Frontpage                                                        :ignore:
*** Authors and Affiliations                                       :ignore:
#+BEGIN_EXPORT latex
%% use the tnoteref command within \title for footnotes;
%% use the tnotetext command for theassociated footnote;
%% use the fnref command within \author or \address for footnotes;
%% use the fntext command for theassociated footnote;
%% use the corref command within \author for corresponding author footnotes;
%% use the cortext command for theassociated footnote;
%% use the ead command for the email address,
%% and the form \ead[url] for the home page:
%% \title{Title\tnoteref{label1}}
%% \tnotetext[label1]{}
%% \author{Name\corref{cor1}\fnref{label2}}
%% \ead{email address}
%% \ead[url]{home page}
%% \fntext[label2]{}
%% \cortext[cor1]{}
%% \address{Address\fnref{label3}}
%% \fntext[label3]{}

\author[UFRGS]{Lucas Mello Schnorr\corref{cor}}
\ead{schnorr@inf.ufrgs.br}

\author[UGA]{Jean-Marc Vincent}
\ead{jean-marc.vincent@imag.fr}

\address[UFRGS]{
Institute of Informatics, Federal University of Rio Grande do Sul -- UFRGS\\
91501-970, Porto Alegre, RS -- Brazil\\
}

\address[UGA]{
Univ. Grenoble Alpes, Inria, CNRS, Grenoble INP, LIG\\
F-38000 Grenoble -- France\\
}

\cortext[cor]{Corresponding author: 
  Tel.: +55 (51) 3308-6822;
}
#+END_EXPORT

*** Abstract                                                       :ignore:

#+LaTeX: \begin{abstract}

This repository is a modification of Schnorr's original document available
on [[https://github.com/schnorr/elsevierorg][his github repository]].
We introduce the possibility of using the new =org-mode= way 
of citing and refering (=org-cite=, =org-ref=) , still letting one to use classic,
more latexian =bibtex= approach. The details are explained in
section [[sec:customization]].

BTW: Put your abstract here.

#+LaTeX: \end{abstract}

*** Graphical Abstract                                             :ignore:

#+latex: %\begin{graphicalabstract}

# Graphical Abstract

#+latex: %\end{graphicalabstract}

*** Research Highlights                                            :ignore:

#+latex: %\begin{highlights}

# \item Research highlight 1
# \item Research highlight 2

#+latex: %\end{highlights}

*** Keywords                                                       :ignore:

#+latex: \begin{keyword}

#+BEGIN_EXPORT latex
%% keywords here, in the form: keyword \sep keyword

%% PACS codes here, in the form: \PACS code \sep code

%% MSC codes here, in the form: \MSC code \sep code
%% or \MSC[2008] code \sep code (2000 is the default)
#+END_EXPORT

#+latex: \end{keyword}
*** Maketitle                                                      :ignore:
#+LaTeX: \maketitle
* *The Paper (content)*                                         :ignore:

** Introduction

This is just an example to show how Orgmode can be
neatly used to write papers following the Elsevier latex style. Feel
free to modify and distributed this as you wish.

Be aware that this example is compatible with OrgMode 9.*.
In fact, in my (MB) case the project is working on Org-mode 9.6,
and Emacs 29.1.

For a detailed explanation on why and how to write reproducible
articles using OrgMode, please visit the following [[https://github.com/alegrand/RR_webinars/blob/master/1_replicable_article_laboratory_notebook/index.org][page]].

** Background and Experimental Context <<sec.context>>
# THIS IS NOT NEEDED IN THIS VERSION OF THE TEMPLATE: \label{sec.context}
*** Background <<sec.background>>
# THIS IS NOT NEEDED IN THIS TEMPLATE: \label{sec.background}
*** Experimental Context and Workload Details <<sec.setup>>
# THIS IS NOT NEEDED IN THIS VERSION OF THE TEMPLATE: \label{sec.setup}
** Related Work and Motivation <<sec.relatedwork>>
# THIS IS NOT NEEDED IN THIS VERSION OF THE TEMPLATE: \label{sec.relatedwork}


** Your Great Contribution to Computer Science <<sec.proposal>>
# THIS IS NOT NEEDED IN THIS VERSION OF THE TEMPLATE: \label{sec.proposal}
** Your Super Results
** Description of MB's Customizations  <<sec:customization>>
*** Internal references - sections
The first improvement over Schnorr's template is the change of way how
references within the document are handled. Instead of using
=\label{}= =\ref{}=
we prefer known from =org-mode=:
=<< >>= for labels and =[ [  ] ]= for inserting link.

Of course you may still use =latex=-ian way of label/reference pairs.
Just try to be consistent over the document. For your own sake :).

**** *Example of preferred way of refering to sections*:
This section number is [[sec:customization]].

**** Example of =latex=-style label/reference scheme \label{sec:ex2}
This section number is equal \ref{sec:ex2}.

**** Example of =org-ref= =latex=-style scheme 
You can also use =org-ref= interface to insert org-mode-buffer-clickable
references which is far more convenient (=M-x org-ref-insert-ref-link=):
=org-ref= reference to this section: ref:sec:ex2.

*** Internal references - equations, floats 
**** Example of floats label/reference scheme
Depeneding on our preference we can use two ways of labeling/referencing
to floats: 
=latex=-like scheme or org-mode =#+NAME= tag.
Choose the one you like more and be consistent.


***** *Example of preferred way of refering to floats*
#+NAME:   tab:A
#+CAPTION: =#+NAME=-tagged table
| XX | YY |
|  1 |  2 |

org-mode =[ [= =] ]= refrence to Table [[tab:A]]. 

***** Example of other =org-ref= way of refering to floats

#+begin_export latex
\begin{table}[htbp]
\centering
\begin{tabular}{rr}
A & a\\[0pt]
1 & 2\\[0pt]
\end{tabular}
\caption{label-tagged table}
\label{tab:B}
\end{table}
#+end_export

 Org-ref =latex=-style reference to Table: ref:tab:B.



**** Example of equation label/reference scheme
When it comes to equations there's only one working way of referencing
to equations, since =#+NAME= labels are not working with =org-ref= for me.

***** *Example of preferred way of refering to equations*

#+begin_export latex
\begin{equation}
E=mc^2
\label{Eq:emc2-label}
\end{equation}
#+end_export

org-ref to =\label= reference: eqref:Eq:emc2-label

***** (NOT WORKING) Example of other =org-ref= way of refering to floats

#+NAME: Eq:emc2-name
#+begin_export latex
\begin{equation}
E=mc^2
\end{equation}
#+end_export

- org-ref reference to the second equation labelled by =#+NAME= tag is currently *not working* for me: ref:Eq:emc2-name

*** Bibliography - two ways of handling citations
When it comes to handling bibliography we also introduce some new
features.
Firstly, we include explicit definition of latex compilation process 
in the first section of the document in the line:

=(setq org-latex-pdf-process ...=.

This is done because the original Schnorr's version of the code
was not working properly at this part.

Secondly, we wanted to use the newer citing engine =org-cite=.
In order to let one conveniently use any of them we decided on defining two
local-buffer tags:

=purelatexEngine= and =@orgciteEngine=. 

If you want to use one of them, you need to put the other one in the line with
=#+EXCLUDE_TAGS:= (the beginning of this file).

\noindent *COMMENT*: Do remember to put excluded tag *before* =noexport= tag
(It does not work otherwise.).

Do decide which citing method you prefer, write the tag name of the other one
in =#+EXCLUDE_TAGS:=, and cite bibliography
items as it is presented below.

*VERY IMPORTANT COMMENT!!!*:

We prefer using =org-cite= engine.
It is the newest approach,
it is built-in into org-mode,
and seems to be more prospective than =org-ref=. 

After invoking =M-x org-cite-insert= a new buffer appears with
the list of all your bibliography items defined in
your bib-file. You can conveniently select appropriate one from the list.
This feature is not available for =bibtex=-like style.

**** *Details on implementing =org-cite= engine (preferred one)*
After setting =org-latex-pdf-process= variable (which is done in the
preamble of this document
you also need to add at the beginning of the document the following:
#+begin_src org
  ,#+BIBLIOGRAPHY: ./refs.bib
  ,#+CITE_EXPORT: csl elsevier-american-chemical-society-without-doi.csl
#+end_src
and
#+begin_src org
  ,#+LATEX:\section*{References}
  ,#+PRINT_BIBLIOGRAPHY: 
#+end_src
at the end of the file.




**** Details on implementing =purelatex=-like style
After setting =org-latex-pdf-process= variable (which is done in the
preamble of this document
you only need to add:
#+begin_src org
  #+LATEX: \bibliographystyle{plain}
  #+LATEX: \bibliography{refs} % where refs is a ref.bib file on your disk
#+end_src
at the end of the file.

**** *Example of citing with =org-cite= engine (preferred one)* :@orgciteEngine:
Currently =orgciteEngine= is enabled.

After tangling bib file from section [ [bib-file-to-tangle] ]
citations are accesible with the following style:

Citations in =orgciteEngine=:

Single citation [cite: @orgmode].

Multiple citations:  [cite: @schnorr2013visualizing; @Schnorr-repo ] can be used.



**** Example of citing with =purelatex=-like style       :purelatexEngine:
Currently =purelatexEngine= is enabled.

After tangling bib file from section [ [bib-file-to-tangle] ]
citations are accesible with the following style:

Citations in =purelatexEngine=:

Single citation \cite{orgmode}.

Multiple citations: \cite{schnorr2013visualizing, Schnorr-repo} can be used.



**** Using custom bibliography styles

Changing bibliography style in =purelatex= engine comes down
to changing =plain= in line =#+LATEX: \bibliographystyle{plain}=
to the style you prefer.

Changing bibliography style in =org-cite= engine comes down
to changing =plain= in line =#+CITE_EXPORT: bibtex plain=
to the style you prefer. You may choose the =.bst= files
included in this repository.

*** Known issues
**** TODO ''PDF file produced with warnings [undefined reference] [undefined citation]''
This is probably the problem with emacs, which seems to gather all
the warnings that occur during compilation described by

=org-latex-pdf-process=

and displays them after the process is finished.
You may see something like:
#+begin_src sh :eval no
pdf file produced with warnings: [undefined reference] [undefined citation]
#+end_src
although all the references and citations are properly numbered.

The problem occurs because these warnings appear during the first iteration of
=pdflatex=-ing, the next =pdflatex= compilations, after
processing with =bibtex= are without these warnings.

You may mimic this situation if you run:
#+begin_src sh :eval no
pdflatex elsevier # + flags that need to be passed to have compilation working 
bibtex elsevier
pdflatex elsevier
pdflatex elsevier
#+end_src

The above commands may also be used to check the correctness
of the paper (last pdflatex run should raise no warnings).

**** TODO *WARNING!!!*: Conflict between =engraved= and =lineno= latex package
By default Schnorr's template had =lineno= latex package
included. In this way you could have lines numbered when exporting
to pdf.
However there exist some conflict between =lineno= and =engraved=
listing backend for org-mode which I'm currently using.
That's why lines with =lineno= needs to be commented out from
the preamble of this file.

It should be noted, that it can be reenabled if you write
a document without =#+begin_src= blocks (or if you
use other listings backends (minted, verbatim...).





** Conclusions

** Acknowledgments                                                  :ignore:

#+LATEX:\section*{Acknowledgements}

Who paid for this?

** References                                                 :ignore:
<<sec:references>>

# See next section to understand how refs.bib file is created.


*** Citation - option 1: =cite-org=                 :ignore:@orgciteEngine:

# ### MB note:  setting latex compilation for cite-org citation approach
#+LATEX:\section*{References}
#+PRINT_BIBLIOGRAPHY: 


*** Citation - option 2: =purelatex=               :ignore:purelatexEngine:
<<citation-bibtex-include-bibliography>>

# ### MB note: uncomment two lines below if you use bibtex citation approach
#+LATEX: \bibliographystyle{plain}
#+LATEX: \bibliography{refs}
  


* Bib file is here                                                 :noexport:
<<bib-file-to-tangle>>

Tangle this file with C-c C-v t

#+begin_src bib :tangle refs.bib
@article{orgmode,
  author =	"Eric Schulte and Dan Davison and Thomas Dye and Carsten Dominik",
  title =	"A Multi-Language Computing Environment for Literate Programming and Reproducible Research",
  journal =	"J. of Stat. Soft.",
  volume =	"46",
  number =	"3",
  day =  	"25",
  year = 	"2012",
  CODEN =	"JSSOBK",
  ISSN = 	"1548-7660",
  bibdate =	"2011-10-03",
  accepted =	"2011-10-03",
  acknowledgement = "",
  submitted =	"2010-12-22",
}

@incollection{schnorr2013visualizing,
  title={Visualizing More Performance Data Than What Fits on Your Screen},
  author={Schnorr, Lucas M and Legrand, Arnaud},
  booktitle={Tools for High Performance Computing 2012},
  pages={149--162},
  year={2013},
  publisher={Springer}
}

@misc{Schnorr-repo,
  title = {Elsevier LaTeX in Org-Mode},
  urldate = {2024-01-13},
  howpublished = {https://github.com/schnorr/elsevierorg}
}


#+end_src
